apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  labels:
    app: grafana-np
spec:
  ports:
    - name: ui
      port: 443
      targetPort: 3000
  selector:
    app: grafana-d
  type: NodePort
