apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres-port
  clusterIP: None
  selector:
    app: postgres