apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-configmap
  namespace: default
data:
  init.sh: |-
    #!/bin/bash
    cp /opt/zookeeper/init/zoo.cfg /opt/zookeeper/conf/zoo.cfg
    cp /opt/zookeeper/init/log4j.properties /opt/zookeeper/conf/log4j.properties

    ZOOKEEPER_ID=${HOSTNAME##*-}
    ADD_ONE=$(echo "$((ZOOKEEPER_ID + 1))")
    echo "${ADD_ONE}" > /data/zookeeper/myid

    echo "" >> /opt/zookeeper/conf/zoo.cfg
    echo "" >> /opt/zookeeper/conf/zoo.cfg

    START=1
    for (( c=$START; c<=$ZOOKEEPER_REPLICAS; c++ ))
    do
      SUB_ONE=$(echo "$((c - 1))")
      echo "server.${c}=zookeeper-${SUB_ONE}.zookeeper.default.svc.cluster.local:2888:3888:participant" >> /opt/zookeeper/conf/zoo.cfg
    done

  zoo.cfg: |-
    # The number of milliseconds of each tick
    tickTime=6000
    # The number of ticks that the initial
    # synchronization phase can take
    initLimit=10
    # The number of ticks that can pass between
    # sending a request and getting an acknowledgement
    syncLimit=5
    # the directory where the snapshot is stored.
    # do not use /tmp for storage, /tmp here is just
    # example sakes.
    dataDir=/data/zookeeper
    # the port at which the clients will connect
    clientPort=2181
    # the maximum number of client connections.
    # increase this if you need to handle more clients
    #maxClientCnxns=60
    #
    # Be sure to read the maintenance section of the
    # administrator guide before turning on autopurge.
    #
    # http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
    #
    # The number of snapshots to retain in dataDir
    #autopurge.snapRetainCount=3
    # Purge task interval in hours
    # Set to "0" to disable auto purge feature

  log4j.properties: |-
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

    # Suppress connection log messages, three lines per livenessProbe execution
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxnFactory=WARN
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxn=WARN
