version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZK_ID: 1
      ZK_CFG_ADDITIONAL: "
      server.1=zookeeper:2888:3888
      "
    volumes:
      - ${PWD}/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
  kafka:
    image: kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    volumes:
      - ${PWD}/server.properties:/opt/kafka/config/server.properties
  kafka-manager:
    image: kafka-manager
    ports: 
      - "7372:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: notsosecret
      KM_ARGS: -Djava.net.preferIPv4Stack=true
